DROP DATABASE IF EXISTS auth;

CREATE DATABASE auth;

USE auth;

CREATE TABLE users(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    email VARCHAR(60) NOT NULL UNIQUE,
    password VARCHAR(400) NOT NULL UNIQUE
);

